## Clean and Transform PVI Data

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv(Path('PartisanVotingIndex_WorldPopulationReview.csv'), index_col=False)
df.head(5)

           State  partisanVotingIndexDemocratic
0        Vermont                          -15.0
1         Hawaii                          -15.0
2  Massachusetts                          -14.0
3       Maryland                          -14.0
4     California                          -14.0

In [3]:
df.rename(columns = {"State": "state_name"}, inplace = True)
df.head(5)

      state_name  partisanVotingIndexDemocratic
0        Vermont                          -15.0
1         Hawaii                          -15.0
2  Massachusetts                          -14.0
3       Maryland                          -14.0
4     California                          -14.0

In [4]:
#create state rank cloumn 
df['state_rank'] = df.index
df.head(5)

      state_name  partisanVotingIndexDemocratic  state_rank
0        Vermont                          -15.0           0
1         Hawaii                          -15.0           1
2  Massachusetts                          -14.0           2
3       Maryland                          -14.0           3
4     California                          -14.0           4

In [5]:
df.dtypes

state_name                        object
partisanVotingIndexDemocratic    float64
state_rank                         int64
dtype: object

In [6]:
# convert Nan's to 0
df['partisanVotingIndexDemocratic'] =df['partisanVotingIndexDemocratic'].fillna(0)

In [7]:
# assign political party based on PVI score
Party = []

for PVI in df['partisanVotingIndexDemocratic']:
    if PVI <= 0:
        Party.append("D")
    else:
        Party.append("R")
Party

['D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R',
 'R']

In [8]:
#add party col to DF
df['party'] = Party
df

        state_name  partisanVotingIndexDemocratic  state_rank party
0          Vermont                          -15.0           0     D
1           Hawaii                          -15.0           1     D
2    Massachusetts                          -14.0           2     D
3         Maryland                          -14.0           3     D
4       California                          -14.0           4     D
5         New York                          -10.0           5     D
6       Washington                           -8.0           6     D
7     Rhode Island                           -8.0           7     D
8         Illinois                           -7.0           8     D
9      Connecticut                           -7.0           9     D
10          Oregon                           -6.0          10     D
11      New Jersey                           -6.0          11     D
12        Delaware                           -6.0          12     D
13      New Mexico                           -3.0          13     D
14        Colorado                           -3.0          14     D
15        Virginia                           -2.0          15     D
16       Minnesota                           -1.0          16     D
17           Maine                           -1.0          17     D
18   New Hampshire                            0.0          18     D
19          Nevada                            0.0          19     D
20        Michigan                            1.0          20     R
21       Wisconsin                            2.0          21     R
22    Pennsylvania                            2.0          22     R
23  North Carolina                            3.0          23     R
24         Georgia                            3.0          24     R
25         Florida                            3.0          25     R
26         Arizona                            3.0          26     R
27            Ohio                            6.0          27     R
28            Iowa                            6.0          28     R
29  South Carolina                            8.0          29     R
30     Mississippi                            9.0          30     R
31          Alaska                            9.0          31     R
32        Missouri                           10.0          32     R
33         Montana                           11.0          33     R
34          Kansas                           11.0          34     R
35         Indiana                           11.0          35     R
36       Louisiana                           12.0          36     R
37            Utah                           13.0          37     R
38        Nebraska                           13.0          38     R
39       Tennessee                           14.0          39     R
40           Texas                           15.0          40     R
41         Alabama                           15.0          41     R
42    South Dakota                           16.0          42     R
43        Kentucky                           16.0          43     R
44        Arkansas                           16.0          44     R
45           Idaho                           19.0          45     R
46        Oklahoma                           20.0          46     R
47    North Dakota                           20.0          47     R
48   West Virginia                           23.0          48     R
49         Wyoming                           26.0          49     R

In [9]:
#drop unneeded column
PVI_df = df.drop(["partisanVotingIndexDemocratic"], axis=1)
PVI_df.head(5)

      state_name  state_rank party
0        Vermont           0     D
1         Hawaii           1     D
2  Massachusetts           2     D
3       Maryland           3     D
4     California           4     D

In [10]:
#set state name as index
#PVI_df.set_index('State_Rank', inplace=True)
#PVI_df.head(5)

## Send PVI Data to Database

In [11]:
from sqlalchemy import create_engine
from getpass import getpass

In [12]:
#store password variable
password = getpass("enter database pw")

enter database pw········

In [13]:
# connect to database
engine = create_engine(f"postgresql://postgres:{password}@localhost:5432/CovidSearchTrends")

In [14]:
# import PVI data to database
PVI_df.to_sql(name="partisan_voting_index", con=engine, index = False, if_exists='append')

## Save PVI Data as CSV

In [15]:
PVI_df.to_csv("..\Resources\partisan_voting_index.csv")